# exam2 due 5p Fri Mar 12 2021

This assignment will be graded on both participation and correctness (1 point each, for a total of 2 points for each sub-problem).

***You are welcome (and encouraged) to:***
* use analytical and numerical computational tools -- specify the tool(s) in sourcecode and/or text;
* reuse example sourcecode and other materials provided in this course;
consult textbooks, websites, and other publicly-available materials -- include full citation(s) with the URL and/or DOI (Links to an external site.).

***You are not permitted to discuss the exam problems or share any part of your solutions with anyone other than the Prof.***

* By submitting your exam solution on Canvas, you are affirming your understanding of and adherence to these restrictions.
* The Prof will be available to answer questions during Zoom time in each exam week.
* The Prof will also answer questions posted to the Canvas Discussion board until 5p Fri in the exam week.

Submit your homework writeup by uploading a .pdf and/or .ipynb on the Canvas Assignment.

You are welcome (and encouraged) to typeset your homework assignments rather than write them by hand.  While you could do this with LaTeX, you may find it easier to use the Colaboratory Notebook, since it is adept at embedding equations (via LaTeX syntax), matrix computations, and control system calculations.



# 0. [preferred name]; [preferred pronouns]

a. Approximately how many hours did you spend on this assignment?

b. Were there specific problems that took much longer than others?

c. What class meeting(s) did you participate in this week?

d. What timezone(s) were you working in this week?


# 1. controllability

Consider (CT-LTI-DE)

$$ \dot{x} = A x + B u,\ x\in\mathbb{R}^n,\ u\in\mathbb{R}^k, $$

and suppose $(A,B)$ is controllable.

(a.) Prove or disprove (e.g. provide a counterexample):  given $\xi\in\mathbb{R}^n$ there exists a control input $\mu:[0,\infty)\rightarrow\mathbb{R}^k$ and a time $\tau > 0$ such that $x(t) = \xi$ for all $t \geq \tau$ (assume $x(0) = 0$), i.e.

$$ \forall \xi\in\mathbb{R}^n : \exists \tau > 0, (\mu:[0,\infty)\rightarrow\mathbb{R}^k) : \forall t \geq \tau : x(t) = \xi. $$

(b.) Prove or disprove (e.g. provide a counterexample):  there exists $K\in\mathbb{R}^{k\times n}$ and time $\tau > 0$ such that full-state feedback $u = - K x$ yields $x(\tau) = 0$ for all $x(0)\in\mathbb{R}^n$.

$$ \exists \tau > 0, K\in\mathbb{R}^{k\times n} : \forall x(0)\in\mathbb{R}^n : u = - K x \implies x(\tau) = 0. $$

# 2. observability

Given LTV-DE

$$ \dot{x} = A(t) x + B(t) u,\ x\in\mathbb{R}^n,\ u\in\mathbb{R}^k, $$

$$ y = C(t) x + D(t) u,\ y\in\mathbb{R}^m, $$

and times $t_0 < t_1$, 
recall the definition of the ***reachable subspace*** $\mathcal{R}[t_0,t_1]$ from Lecture 04a,
and define the ***output-reachable subspace*** $\mathcal{S}[t_0,t_1]\subset\mathbb{R}^m$ by

$$ \mathcal{S}[t_0,t_1] = \left\{ C(t_1)\int_{t_0}^{t_1} \Phi(t_1,\tau) B(\tau) u(\tau) d\tau + D(t_1) u(t_1) \mid u:[t_0,t_1]\rightarrow\mathbb{R}^k \right\}. $$

We say (LTV-DE) is:
* ***reachable on $[t_0,t_1]$*** if $\mathcal{R}[t_0,t_1] = \mathbb{R}^n$;
* ***output-reachable on $[t_0,t_1]$*** if $\mathcal{S}[t_0,t_1] = \mathbb{R}^m$.

(a.) Prove or disprove (e.g. provide a counterexample): if (LTV-DE) is reachable then it is output-reachable.

(b.) Prove or disprove (e.g. provide a counterexample): if (LTV-DE) is output-reachable then it is reachable.



# 3. closing the loop

Consider (LTI-DE)

$$ \dot{x}/x^+ = A x + B u,\ x\in\mathbb{R}^n,\ u\in\mathbb{R}^k, $$

$$ y = C x + D u,\ y\in\mathbb{R}^m, $$

and suppose $(A,B)$ controllable, $(A,C)$ observable.

(a.) Prove or disprove (e.g. provide a counterexample):  for all $K\in\mathbb{R}^{k\times n}$, $(A - B K, B)$ is controllable.

(b.) Prove or disprove (e.g. provide a counterexample):  for all $K\in\mathbb{R}^{k\times n}$, $(A - B K, C)$ is observable.

# 4. MIMO systems

Consider the following block diagram involving a MIMO process $P$ and MIMO controller $C$ built from two MIMO subsystems (feedforward $F$ and feedback $B$):

![](https://docs.google.com/drawings/d/e/2PACX-1vR_Pnr7CfFqFJqAOeURp3SpJmx6C98NhNpU-c6vESPEizdQd2cjsBBsBEnUmGAzG-nNtuVoyTjRi4ae/pub?w=576&h=260)

(a.) Derive transfer matrices $T_{yr}$ and $T_{yd}$.

(b.) Determine necessary conditions on $C$ (i.e. on $F$ and $B$) and $P$ such that $T_{yr} = I$ (i.e. the transformation from $r$ to $y$ is the identity); be sure to carefully consider and explicitly state all assumptions.

# 5. computation

Consider the simplified vertical-plane quadrotor model
$$ M\ddot{\eta} = F\sin\theta, $$
$$ M\ddot{\nu} = -Mg + F\cos\theta, $$
$$ I\ddot{\theta} = \tau $$
where ($\eta$, $\nu$) denote the quadrotor (horizontal, vertical) position and $\theta$ denotes the quadrotor's rotation, ($M$, $I$) denote quadrotor (mass, inertia), $g$ is acceleration due to gravity, and ($F$, $\tau$) denote the net (thrust, torque) applied by the spinning rotors.

With $q = (\eta,\nu,\theta)\in\mathbb{R}^3$ denoting positions and $\dot{q} = \frac{d\ }{dt} q = (\dot{\eta},\dot{\nu},\dot{\theta})\in\mathbb{R}^3$ denoting velocities,
the state vector is $x = (q,\dot{q})\in\mathbb{R}^6$,
the input vector is $u = (F,\tau)\in\mathbb{R}^2$,
and the state-space model is
$$ \dot{x} = \frac{d}{dt}\left[\begin{array}{c} q \\ \dot{q} \end{array}\right] = \left[\begin{array}{c} \dot{q} \\ \ddot{q}(x,u) \end{array}\right] = f(x,u), $$
where $\ddot{q} : \mathbb{R}^6 \times \mathbb{R}^2 \rightarrow \mathbb{R}^3$ is defined by 
$$\ddot{q}(x,u) = \left[\begin{array}{c} \frac{F}{M}\sin\theta \\ -g + \frac{F}{M}\cos\theta \\ \frac{\tau}{I}\end{array}\right].$$ 

Finally, suppose the planar position (but not rotation) of the quadrotor is measured:

$$ y = h(x,u) = \left[\begin{array}{c} \eta \\ \nu \end{array}\right]. $$

Note that $\dot{q}_0 = 0$ (i.e. zero velocity) is an equilibrium with any position $q_0 = (\eta,\nu,0)$ when input $u = (Mg,0)$ (i.e. thrust balances force of gravity $Mg$ and torque is zero), so we'll consider one such equilibrium at height $\nu = 1$, i.e.  $q_0 = (0,1,0)$.

(a.) Synthesize and implement an observer-based controller that stabilizes the (LTI-DE) obtained by linearizing the nonlinear system at $(q_0,\dot{q}_0)$.

(b.) Implement the controller from (a.) to stabilize the equilibrium $(q_0,\dot{q}_0)$ in the ***nonlinear*** system.

In both (a.) and (b.), provide simulation sourcecode and plots that illustrate convergence to equilibrium.  Helpful functions are provided below.

In [5]:
def Jacobian(g,y,d=1e-4):
  """
  approximate derivative via finite-central-differences 

  input:
    g - function - g : R^n -> R^m
    y - n array
    (optional)
    d - scalar - finite differences displacement parameter

  output:
    Dg(y) - m x n - approximation of Jacobian of g at y
  """
  # given $g:\mathbb{R}^n\rightarrow\mathbb{R}^m$:
  # $$D_y g(y)e_j \approx \frac{1}{2\delta}(g(y+\delta e_j) - g(y - \delta e_j)),\ \delta\ll 1$$
  e = np.identity(len(y))
  Dyg = []
  for j in range(len(y)):
      Dyg.append((.5/d)*(g(y+d*e[j]) - g(y-d*e[j])))
  return np.array(Dyg).T

def numerical_simulation(f,t,x,t0=0.,dt=1e-4,ut=None,ux=None,utx=None,return_u=False):
  """
  simulate x' = f(x,u) 

  input:
    f : R x X x U --> X - vector field
      X - state space (must be vector space)
      U - control input set
    t - scalar - final simulation time
    x - initial condition; element of X

    (optional:)
    t0 - scalar - initial simulation time
    dt - scalar - stepsize parameter
    return_u - bool - whether to return u_

    (only one of:)
    ut : R --> U
    ux : X --> U
    utx : R x X --> U

  output:
    t_ - N array - time trajectory
    x_ - N x X array - state trajectory
    (if return_u:)
    u_ - N x U array - state trajectory
  """
  t_,x_,u_ = [t0],[x],[]
  
  inputs = sum([1 if u is not None else 0 for u in [ut,ux,utx]])
  assert inputs <= 1, "more than one of ut,ux,utx defined"

  if inputs == 0:
    assert not return_u, "no input supplied"
  else:
    if ut is not None:
      u = lambda t,x : ut(t)
    elif ux is not None:
      u = lambda t,x : ux(x)
    elif utx is not None:
      u = lambda t,x : utx(t,x)

  while t_[-1]+dt < t:
    if inputs == 0:
      _t,_x = t_[-1],x_[-1]
      dx = f(t_[-1],x_[-1]) * dt
    else:
      _t,_x,_u = t_[-1],x_[-1],u(t_[-1],x_[-1])
      dx = f(_t,_x,_u) * dt
      u_.append( _u )

    x_.append( _x + dx )
    t_.append( _t + dt )

  if return_u:
    return np.asarray(t_),np.asarray(x_),np.asarray(u_)
  else:
    return np.asarray(t_),np.asarray(x_)

In [16]:
import numpy as np

g,M,I = 9.81,1.,1. # m/sec^2, kg, kg m^2

def f(t,x,u):
    q,dq = x[:3],x[3:] # positions, velocities
    eta,nu,theta = q # horiz., vert., rotation
    F,tau = u # thrust, torque
    return np.hstack([dq,(F/M)*np.sin(theta),
                        -g + (F/M)*np.cos(theta),
                        tau/I])

def h(t,x,u):
    q,dq = x[:3],x[3:] # positions, velocities
    return q[:2]

In [17]:
q0 = np.array([0.,1.,0.])
dq0 = np.array([0.,0.,0.])
x0 = np.hstack((q0,dq0))
u0 = np.array([M*g,0.])
print('x0 =',x0,'\nf(x0) =',f(0.,x0,u0))

A = Jacobian(lambda x : f(0.,x,u0),x0)
B = Jacobian(lambda u : f(0.,x0,u),u0)
C = Jacobian(lambda x : h(0.,x,u0),x0)
D = Jacobian(lambda u : h(0.,x0,u),u0)

print('A =\n',A)
print('B =\n',B)
print('C =\n',C)
print('D =\n',D)

x0 = [0. 1. 0. 0. 0. 0.] 
f(x0) = [0. 0. 0. 0. 0. 0.]
A =
 [[0.         0.         0.         1.         0.         0.        ]
 [0.         0.         0.         0.         1.         0.        ]
 [0.         0.         0.         0.         0.         1.        ]
 [0.         0.         9.80999998 0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]]
B =
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 1.]]
C =
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]
D =
 [[0. 0.]
 [0. 0.]]


It is straightforward to confirm that the linearized system is controllable and observable:

In [15]:
Co = np.hstack((B,A@B,A@A@B,A@A@A@B))
np.linalg.matrix_rank(Co)

6

In [18]:
O = np.vstack((C,C@A,C@A@A,C@A@A@A))
np.linalg.matrix_rank(O)

6